name: Development


on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    
    steps:

      - name: Setup .NET SDK
        uses: actions/checkout@v2
        with:
          dotnet-version: 7.x
        
      - name: Restore nuget packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build

      - name: Run unit tests
        run: dotnet test

      
      - name: Publish webAPI project
        run: dotnet publish src/WebApi -o publish
      

